### ISSUE TITLE
Implementing Navbar/Hiding Functionality for Members Page

### ISSUE THREAD

**Issue by HarryChui** [cmubtg/website#73]

**Comment by dyou3968** [comment]
One small thing I noticed: When you hover over a member, there isn't any indication that a user can click on the photo to go to the individual member page. I think it's best to add a visual change to the cursor when a user is over the member so that they know they can click on the photo and go to the individual member page.

**Comment by HarryChui** [comment]
I've been looking, but I can't find anything about being able to add that feature. Maybe we just write that the pictures are clickable in the grey box at the top of the page?

**Comment by HarryChui** [comment]
Nevermind, I was able to fix it!
